CREATE DATABASE IF NOT EXISTS todo;
USE todo;
CREATE TABLE IF NOT EXISTS todoItems (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    itemDescription VARCHAR(100),
    completed BOOLEAN DEFAULT FALSE
);
SELECT * FROM todoItems;